name: conference_app
description: A conference app built with Flutter.
publish_to: "none"
version: 1.0.1+10100

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.1
  card_swiper: ^2.0.4
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.8.0
  collection: ^1.16.0
  firebase_analytics: ^10.4.2
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  firebase_remote_config: ^4.2.2
  flame: ^1.3.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.5
  flutter_local_notifications: ^14.1.1
  flutter_native_splash: ^2.2.7
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.6
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.2.0
  go_router: ^7.1.1
  google_fonts: ^4.0.4
  hive_flutter: ^1.1.0
  html: ^0.15.3
  http: ^0.13.5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.5
  webview_flutter: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  vector_math: ^2.1.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcherIcon_android.png"
  image_path_ios: "assets/icons/launcherIcon_ios.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#00063B"
  image: assets/images/splash_image_light.png
  image_dark: assets/images/splash_image_dark.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
